ALTER TABLE tb_user ADD birth_date DATE;
ALTER TABLE tb_user ADD created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_user ADD updated_at TIMESTAMP;

ALTER TABLE tb_exercise ADD created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_exercise ADD updated_at TIMESTAMP;

ALTER TABLE tb_workout ADD created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_workout ADD updated_at TIMESTAMP;

ALTER TABLE tb_workout_exercise ADD created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_workout_exercise ADD updated_at TIMESTAMP;